version: '3'
services:
  smarttrip-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RAILWAY_PORT: $PORT
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
