services:
  - type: web
    name: smarttrip-backend
    env: java
    plan: free
    branch: main
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    autoDeploy: true
