spring.application.name=smarttrip

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/smarttrip
spring.datasource.username=root
spring.datasource.password=FirstSQLpass69#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
